#!/bin/sh
set -e

ABUILDHOME=/drone

# Create abuild user
adduser -h $ABUILDHOME -G abuild -D abuild
# Add user to fuse group for sshfs purposes
addgroup -S fuse || true
adduser abuild fuse
chown abuild:abuild $ABUILDHOME
echo "abuild    ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Ensure the abuild user has full permissions
if [ -n "$DRONE_WORKSPACE" ]; then
    chown abuild:abuild -R "$DRONE_WORKSPACE"
fi

apk update

exec su-exec abuild:abuild /usr/local/bin/run-abuild
